#!/usr/bin/env bash

if [ ! -z "$DTM" ]
then
	. ${DTM}/env.sh
else
	. $(dirname "${BASH_ARGV[0]}")/env.sh
	if [ -z "$DTM" ]
	then
		echo "env.sh not loaded, aborting!"
		exit 1
	fi
fi

if [ -z "$1" ]
then
    # Stop all running servers!
    for s in $(find $DTM_WATCH -type l)
    do
        echo "Stopping $s"
        svc -d $s
        #svstat $s
    done
else
    echo "Leaving servers UP"
fi

spid=$(ps waux | grep "./svscanboot" | grep -v grep | awk '{ print $2 }')
# echo "pid($spid)"
if [ ! -z "$spid" ]
then
	kill -9 $spid
fi

$KILLALL svscan || echo "No running svscan"
$KILLALL supervise || echo "No running supervise"
$KILLALL readproctitle || echo "No running readproctitle"

