#!/usr/bin/env bash


. $(dirname "${BASH_ARGV[0]}")/env.sh

spid=$(ps waux | grep "./svscanboot" | grep -v grep | awk '{ print $2 }')
# echo "pid($spid)"
if [ ! -z "$spid" ]
then
	kill -9 $spid
fi

$KILLALL svscan || echo "No running svscan"
$KILLALL supervise || echo "No running supervise"

