#!/usr/bin/env bash


spid=$(ps waux | grep "./svscanboot" | grep -v grep | awk '{ print $2 }')
# echo "pid($spid)"
if [ ! -z "$spid" ]
then
	kill -9 $spid
fi

killall svscan || echo "No running svscan"
killall supervise || echo "No running supervise"
